# Generated by Django 5.0.4 on 2024-04-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Calc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fnum', models.FloatField()),
                ('oprator', models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=50)),
                ('lnum', models.FloatField()),
            ],
        ),
    ]
