# Generated by Django 5.0.4 on 2024-04-16 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='fnum',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='calc',
            name='lnum',
            field=models.FloatField(blank=True),
        ),
    ]
