# Generated by Django 5.0.4 on 2024-04-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcApp', '0002_alter_calc_fnum_alter_calc_lnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='fnum',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calc',
            name='lnum',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
