# Generated by Django 5.0.4 on 2024-04-16 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calcApp', '0003_alter_calc_fnum_alter_calc_lnum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calc',
            name='oprator',
            field=models.CharField(choices=[('+', '+'), ('-', '-'), ('*', '*'), ('/', '/')], max_length=50, null=True),
        ),
    ]
